### ISSUE TITLE
update script for pulling variants to deal with refseq variants

### ISSUE THREAD

**Issue by msingerb** [macarthur-lab/variant-curation-portal#227]
Since the hail table now has the refseq annotations as well I think for now we want to exclude these annotations from future projects and only curate those that are visible in the browser as Lof. This means we only want annotations of LoF variants in ensembl transcripts.

**Comment by nawatts** [comment]
The script in this repository filters transcript consequences based on the provided gene IDs. So as long as Ensembl gene IDs are given, it would not include consequences for RefSeq transcripts.

https://github.com/macarthur-lab/variant-curation-portal/blob/2a466c9437b3eb45e42422fb72e6577c4131bbc8/scripts/get_gnomad_lof_variants.py#L162-L170

Based on Slack messages, my best guess is that variants for some projects were pulled using a different version of the script that filtered by gene **symbol** instead of ID. That would include both Ensembl and RefSeq consequences, since they both have the same gene symbols.
